### ISSUE TITLE
TextSortWidget, scrolling & dragging

### ISSUE THREAD

**Issue by Maroben** [phish108/MoblerCards#15]
Its not possible to scroll if the entire window is full of list elements.

The drag function won't stop at the last list element, will continue into infinite white space.

The scrolling is not very smooth.

**Comment by phish108** [comment]
Scrolling is handled by answerview (doScroll) 

- scrolling should be active by default
- when dragging scrolling should be activated only if the touch is in the header or button area
- use fake element to place the drag item to a location.
- at top one needs to be able to scroll above the first element
- at bottm one needs to be able to scroll beyond the last element
